# -*- coding: utf-8 -*-
"""smallest_number.ipynb

Automatically generated by Colab.



a = 15
b = 7
c = 22

# Method 1: Using logic gates
if a <= b and a <= c:
    smallest = a
elif b <= a and b <= c:
    smallest = b
else:
    smallest = c

print(f"The smallest number is: {smallest}")